language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'

install:
  - pip install .
  - pip install tox

script:
  - env
  - tox -e py$( echo $TRAVIS_PYTHON_VERSION | tr -d . )

jobs:
  include:
    - stage: deploy
      python: '3.6'
      install: skip
      script: skip
      deploy:
        provider: pypi
        username: nonspecialist
        password:
          secure: IYt07ycigFijeDIuxojx+TIXSuqeRkHktUi7tBcIlHv7qs3YwiZYnpzKvdw/iTlq4wJduWA64Aad6hWlMptCC//jRiqmXE+LHCcS9jTqwhOOZAT+PrWkOnqkrpImhW1P9+LM5Sm6G0WNh7bukiQadgWoXpvdU/OSMJtAOU0pPecVSdM/73CoxjiRSkO+HDfSNjkCOVahGECN9vnsl0ra6ZpHcmxkKSiUha2NW2LUpDjcFF/MZzKaUeO5EEsql2CVTLu8136lHBxC+Rw0sRnQTWCsGBRyp0JzLNzCbUOwh38XSv4ybgmGaWgDct8LfNeu96qADO5nPFmIMd6+sw0nTtskAvPsrVwpmP1gr1HE77X/m+WTILkaSgmFwpQ7HX1VRDkKcNydG1Gl25KOImp4dcgsxBYgucS1R5g7RwAMaNaCUPyKOI7S+4QlXjlXhtQiVJa5ilZB75xjKULbJB5oa5d1q5ekJwyp6HuSsRO46w5fxOQcOxDW7WMMoWtHTokF+HrscltB450HcVsnFZUg+imqpZOo7oJuVXUY8e5a8smtQZTdRsnbO1cPzzgb1cIx6cCA3+MilncJAbgUmNzNjE1d7+PtEMks3Z8LOdQVDcJvRuWgLYq9+agJq4qnzsCLkDAUNHcjsbnmHkmK7fhG3/mWZ/DGnIYq5fcZ1H6Nhlk=
        on:
          tags: true
